name: build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      ARTIFACT_PATH: build_artifact
      TARGET_DEPLOY_PATH: beef
      PROCESS_NAME: Beef
      PROCESS_USER_NAME: Administrator

    environment: Release

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '9.x'
      - name: build and publish the artifacts
        run: dotnet publish -o ${{ env.ARTIFACT_PATH }}

      - name: populate settings
        uses: microsoft/variable-substitution@v1 
        with:
          files: ${{ env.ARTIFACT_PATH }}/appsettings.json
        env:
          DiscordOptions.Token: ${{ secrets.DISCORD_TOKEN }}
          TelegramOptions.Token: ${{ secrets.TELEGRAM_TOKEN }}
          GoogleOptions.SearchEngineId: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
          GoogleOptions.ApiKey: ${{ secrets.GOOGLE_API_KEY }}
          OpenAiOptions.ApiKey: ${{ secrets.OPENAI_APIKEY }}
          OpenAiOptions.CompletionModelName: ${{ secrets.OPENAI_MODELNAME }}

      - name: terminate remote process
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: pkill -f ${{ env.PROCESS_NAME }}

      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ${{ env.ARTIFACT_PATH }}
          target: ${{ env.TARGET_DEPLOY_PATH }}
          strip_components: 1

      - name: restart remote process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ env.TARGET_DEPLOY_PATH }}
            nohup ./${{ env.PROCESS_NAME }} 1>std.out 2> err.out < /dev/null &